version: '3'
services:
  db:
    container_name: board-db-1
    image: mariadb:latest
    environment:
      - "MYSQL_DATABASE=kotlin_board"
      - "MYSQL_ROOT_PASSWORD=1234"
      - "MYSQL_USER=kb"
      - "MYSQL_PASSWORD=1234"
      - "TZ=Asia/Seoul"
    ports:
      - "3307:3306"
    volumes:
      # DB 데이터 저장 디렉터리
      - ./data:/var/lib/mysql
      # 설정 파일 저장될 위치
      - ./config:/etc/mysql/conf.d
#      - ~/docker/mariadb/etc/mysql/conf.d:/etc/mysql/conf.d:ro
#      - ~/docker/mariadb/var/lib/mysql:/var/lib/mysql
#      - ~/docker/mariadb/var/log/maria:/var/log/maria
    command:
      - sh -c "apt-get update && apt-get install -y mysql-client && docker-entrypoint.sh mysqld"
      - --character-set-server=utf8mb4
  client:
    image: mariadb:10.7
    entrypoint: sh -c 'until mysql -h "board-db-1" -u testuser -ptestpassword -e "SELECT 1" --silent; do echo "Waiting for MariaDB..."; sleep 5; done'
    depends_on:
      - board-db-1


