version: '3'
services:
  db:
    container_name: board-db-1
    image: mariadb:latest
    environment:
      - "MYSQL_DATABASE=kotlin_board"
      - "MYSQL_ROOT_PASSWORD=1234"
      - "MYSQL_USER=kb"
      - "MYSQL_PASSWORD=1234"
      - "TZ=Asia/Seoul"
    ports:
      - "3307:3306"
    volumes:
      # DB 데이터 저장 디렉터리
      - ./data:/var/lib/mysql
      # 설정 파일 저장될 위치
      - ./config:/etc/mysql/conf.d
#      - ~/docker/mariadb/etc/mysql/conf.d:/etc/mysql/conf.d:ro
#      - ~/docker/mariadb/var/lib/mysql:/var/lib/mysql
#      - ~/docker/mariadb/var/log/maria:/var/log/maria
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
  client:
    image: mariadb:10.7
    depends_on:
      - db


