server:
  port: 8080 #?? ?? ??
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      force: true
spring:
  datasource: #?? DB??
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/kotlin_board
    username: kb
    password: 1234
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
  properties:
    hibernate:
      show_sql: true
      format_sql: true
      highlight_sql: true
logging:
  pattern:
    console: "[%d{HH:mm:ss.SSS}][%-5level][%logger.%method:line%line] - %msg%n"
  level:
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.SQL: DEBUG
