name: SonarCloud
on:
  push:
    branches: [main, develop]
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - uses: getong/mariadb-action@v1.1
        with:
          host port: 3306 
          container port: 3306 
          character set server: 'utf8mb4'
          collation server: 'utf8mb4_general_ci'
          mysql database: 'some_test'
          mysql root password: ${{ secrets.RootPassword }}
          mysql user: 'kb'
          mysql password: ${{ secrets.DatabasePassword }}
          
      - name: Set permissions for gradlew
        run: chmod +x ./gradlew
        
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'
          
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew build jacocoTestReport sonar --info

      - name: Shutdown Docker Compose
        run: docker-compose down
