name: Docker Compose CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  docker-compose-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: sudo apt-get update && sudo apt-get install -y docker-compose

      - name: Build and run Docker Compose services
        run: docker-compose up -d --build

      - name: Wait for MariaDB to be ready
        run: |
          docker-compose run --rm client sh -c 'until mysql -h "board-db-1" -u kb -p1234 -e "SELECT 1" --silent; do echo "Waiting for MariaDB..."; sleep 5; done'

      - name: Run tests
        run: docker-compose exec app ./gradlew test --info

      - name: Shutdown Docker Compose
        run: docker-compose down
